services:
  - type: web
    name: panda-market-sprint6
    runtime: node
    plan: free
    region: singapore
    branch: express-박순창-sprint6
    rootDir: sprint6/backend
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: panda-market-db
          property: connectionString

databases:
  - name: panda-market-db
    plan: free